In [1]:
import pandas as pd
import datetime

In [2]:
#load dữ liệu vào data frame
df = pd.read_excel("D:\DA_Camp\data.xlsx")
df

,Số lượng đơn hàng theo khách hàng và theo ngày tạo đơn hàng,create_date,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Unnamed: 97,Unnamed: 98,Unnamed: 99,Unnamed: 100
0,visitor_id,43770,43771,43772,43773,43774,43775,43776,43777,43778,...,43860,43861,43862,43863,43864,43865,43866,43867,43868,43869
1,//02MonW5iVsFHTYioKFKD3J+v0=,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,//0Tw4uLP4F+KxJiH1MxeipBtlc=,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,//1B47ThoPLHFC+ISAeK5lpiquc=,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,//ioYjFoyckJezLI/waPP7iCqtg=,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39436,ZzvqjNiAiYOCnkxl27mQEL1PbZk=,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39437,zzWdLg/Dyw9eyko6k+ZSDUuTio0=,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39438,zzxiPB4vtRlO3eKR9TsP2+iQapc=,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39439,ZzxNkankvZpO6O7TFz4wNb0KE3E=,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39440,Khách vãng lai,2889,2489,2684,2363,2235,2254,1965,1949,1656,...,887,1076,836,801,1036,993,1089,858,907,769

In [5]:
# Đưa dòng đầu lên làm headers
df.columns = df.iloc[0]
df = df[1:]
df

In [ ]:
# unpivot
# Lưu ý: đặt noOrders có nghĩa là number of Orders
df_melted = df.melt(id_vars= df.columns[0], var_name= "create_datenum", value_name= "noOrders")
df_melted

In [9]:
# Tạo thêm cột ngày từ việc quy đổi 43770 đến 43869 ra 1/11/2019 đến 8/2/2020
list = df_melted["create_datenum"].unique()
dict = {}
day = datetime.date(2019, 11, 1)
tdelta = datetime.timedelta(days = 1)
for item in list:
    dict[item] = str(day)
    day = day + tdelta

list = []
for i in df_melted.index:
    list.append(dict[df_melted['create_datenum'][i]])
df_melted["create_date"] = list

df_melted

In [13]:
# Bỏ cột create_datenum vì không cần thiết
df_melted = df_melted.drop(labels= 'create_datenum', axis=1)

In [14]:
# Lưu file
df_melted.to_csv("D:\\DA_Camp\\adjusted_data.csv", index = False)